function showModal(html){document.getElementById('modalBox').innerHTML=html;document.getElementById('modal').classList.remove('hidden');}
function closeModal(){document.getElementById('modal').classList.add('hidden');BE.editMenu=null;}
function login(){const u=document.getElementById('loginUser').value.trim().toUpperCase(),p=document.getElementById('loginPin').value.trim();const users=BE.settings.USERS||DEFAULT_USERS;const f=users.find(v=>v.code===u&&v.pin===p);if(!f){document.getElementById('loginError').textContent='รหัสผู้ใช้หรือรหัสผ่านไม่ถูกต้อง';return;}BE.me=f;document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('userName').textContent=f.name;BE.hotel=f.hotel||'QL';if(f.role==='sales')document.querySelector('[data-hotel="'+f.hotel+'"]').disabled=false;renderAll();}
function logout(){location.reload();}
function setHotel(h){if(BE.me?.role==='sales'&&h!==BE.me.hotel)return;BE.hotel=h;document.querySelectorAll('#hotelTabs button').forEach(b=>b.classList.toggle('active',b.dataset.hotel===h));document.documentElement.dataset.hotel=h;document.getElementById('hotelTitle').textContent=h==='ALL'?'รวม 2 แห่ง':h==='BY'?'Baiyoke Sky':'Queensland';renderEvents();}
function switchView(v){BE.view=v;document.querySelectorAll('.nav-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.getElementById('view-events').classList.toggle('hidden',v!=='events');document.getElementById('view-settings').classList.toggle('hidden',v!=='settings');if(v==='settings')renderSettings();}
function boot(){initDB();BE.settings.MENUS=clone(window.CURRENT_DEFAULT_MENUS||{});BE.settings.ROOMS=clone(DEFAULT_ROOMS);BE.settings.KINDS=clone(DEFAULT_KINDS);BE.settings.STAFF=clone(DEFAULT_STAFF);BE.settings.DEPTS_BASIC=clone(DEFAULT_DEPTS);BE.settings.USERS=clone(DEFAULT_USERS);dbLoad().then(()=>{document.getElementById('loginBtn').disabled=false;});}
function renderAll(){setHotel(BE.hotel);renderEvents();renderSettings();}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('loginBtn').addEventListener('click',login);document.getElementById('logoutBtn').addEventListener('click',logout);document.getElementById('loginPin').addEventListener('keydown',e=>{if(e.key==='Enter')login();});document.querySelectorAll('#hotelTabs button').forEach(b=>b.addEventListener('click',()=>setHotel(b.dataset.hotel)));document.querySelectorAll('.nav-tabs button').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));document.querySelectorAll('.settings-tabs button').forEach(b=>b.addEventListener('click',()=>{BE.settingsView=b.dataset.settings;document.querySelectorAll('.settings-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderSettings();}));document.getElementById('addEventBtn').addEventListener('click',openAddEvent);document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal();});boot();});
setInterval(syncNow,2500);
