function eventTotal(x){return (x.rev||[]).reduce((s,r)=>s+Number(r.price||0)*Number(r.qty||0)*Number(r.times||1),0);}
function formatDate(d){if(!d)return "—";const [y,m,day]=d.split("-");return `${day}/${m}/${y}`;}
function roomOptions(hotel,selected=""){return (BE.settings.ROOMS?.[hotel]||DEFAULT_ROOMS[hotel]||[]).map(r=>`<option ${r===selected?'selected':''}>${esc(r)}</option>`).join("");}
function renderEvents(){
  const list=document.getElementById("eventList");const xs=BE.funcs.filter(visibleEvent).filter(x=>BE.hotel==="ALL"||x.hotel===BE.hotel);
  if(!xs.length){list.innerHTML=`<div class="empty card"><div class="empty-icon">＋</div><h3>ยังไม่มีงาน</h3><p>กด “เพิ่มงาน” เพื่อสร้างใบสั่งงานใหม่</p><button class="primary" onclick="openAddEvent()">＋ เพิ่มงาน</button></div>`;return;}
  const sorted=[...xs].sort((a,b)=>String(a.days?.[0]?.d||"").localeCompare(String(b.days?.[0]?.d||"")));
  list.innerHTML=sorted.map(x=>renderEventCard(x)).join("");
}
function renderEventCard(x){
  const rooms=[...new Set((x.days||[]).map(d=>d.room).filter(Boolean))].join(" / ");
  return `<article class="event-card ${x.hotel==="BY"?'by':''}"><div class="event-date"><b>${x.days?.[0]?.d?new Date(x.days[0].d+"T00:00:00").getDate():"—"}</b><span>${x.days?.[0]?.d?new Date(x.days[0].d+"T00:00:00").toLocaleDateString("th-TH",{month:"short"}):""}</span></div><div class="event-main"><div class="event-top"><span class="badge">${x.hotel==="BY"?"Baiyoke Sky":"Queensland"}</span><span class="muted">${esc(x.kind||"งานจัดเลี้ยง")}</span><span class="muted">ใบสั่งงาน ${esc(x.no||"—")}</span></div><h3>${esc(x.title||"ไม่ระบุชื่องาน")}</h3><p>${esc(x.days?.[0]?.time||"")} · ${esc(rooms)}</p><div class="chips"><span class="badge ok">${esc(x.status||"ร่าง")}</span><span class="badge">${esc(x.doc||"Draft")}</span><span class="badge">${money(x.guarantee||0)} ${esc(x.unit||"ท่าน")}</span>${eventTotal(x)?`<b class="amount">${money(eventTotal(x))} บาท</b>`:""}</div><div class="event-actions"><button class="ghost" onclick="openEvent('${x.id}')">เปิดใบสั่งงาน</button><button class="ghost" onclick="openEditEvent('${x.id}')">แก้ไขงาน</button><button class="ghost" onclick="openMenuEditor('${x.id}',0)">✏️ แก้อาหาร</button></div></div></article>`;
}
function openEvent(id){const x=BE.funcs.find(v=>v.id===id);if(!x)return;showModal(`<div class="modal-title"><div><h3>${esc(x.title)}</h3><p>${x.hotel==='BY'?'Baiyoke Sky':'Queensland'} · ใบสั่งงาน ${esc(x.no)}</p></div><button class="icon" onclick="closeModal()">×</button></div><div class="detail-grid"><div><span>วันที่</span><b>${formatDate(x.days?.[0]?.d)}</b></div><div><span>เวลา</span><b>${esc(x.days?.[0]?.time||'—')}</b></div><div><span>ห้อง</span><b>${esc(x.days?.[0]?.room||'—')}</b></div><div><span>ผู้รับผิดชอบ</span><b>${esc(x.sales||'—')}</b></div></div>${renderMenuSummary(x)}<div class="modal-actions"><button class="ghost" onclick="openEditEvent('${x.id}')">แก้ไขงาน</button><button class="primary" onclick="closeModal()">ปิด</button></div>`);}
function openAddEvent(){
  let defaultHotel=BE.hotel;
  if(defaultHotel==="ALL")defaultHotel="QL";
  if(BE.me.role==="sales")defaultHotel=BE.me.hotel;
  openEventForm(null,defaultHotel);
}
function openEditEvent(id){const x=BE.funcs.find(v=>v.id===id);if(!x)return;BE.editEventId=id;openEventForm(x,x.hotel);}
function openEventForm(x,hotel){
  if(BE.me.role!=="admin"&&BE.me.role!=="sales"){toast("บัญชีนี้ไม่มีสิทธิ์เพิ่ม/แก้งาน");return;}
  const rooms=BE.settings.ROOMS?.[hotel]||DEFAULT_ROOMS[hotel];const kinds=BE.settings.KINDS||DEFAULT_KINDS;const staff=BE.settings.STAFF||DEFAULT_STAFF;
  showModal(`<div class="modal-title"><div><h3>${x?'แก้ไขงาน':'เพิ่มงานใหม่'}</h3><p>${x?'แก้ข้อมูลใบสั่งงานเดิม':'สร้างงานของ '+(hotel==='BY'?'Baiyoke Sky':'Queensland')}</p></div><button class="icon" onclick="closeModal()">×</button></div>
  <div class="form-grid"><label>โรงแรม<select id="fHotel" onchange="changeEventHotel()" ${BE.me.role==='sales'?'disabled':''}><option value="QL" ${hotel==='QL'?'selected':''}>Queensland</option><option value="BY" ${hotel==='BY'?'selected':''}>Baiyoke Sky</option></select></label><label>ประเภทงาน<select id="fKind">${kinds.map(k=>`<option ${k===(x?.kind||'ประชุมสัมมนา')?'selected':''}>${esc(k)}</option>`).join('')}</select></label><label>เลขที่ใบสั่งงาน<input id="fNo" value="${esc(x?.no||'')}"></label><label>สถานะ<select id="fStatus"><option ${x?.status==='รอมัดจำ'?'selected':''}>รอมัดจำ</option><option ${x?.status==='ยืนยันแล้ว'?'selected':''}>ยืนยันแล้ว</option><option ${x?.status==='ปิดงานแล้ว'?'selected':''}>ปิดงานแล้ว</option></select></label><label class="wide">ชื่องาน<input id="fTitle" value="${esc(x?.title||'')}"></label><label>วันที่<input id="fDate" type="date" value="${esc(x?.days?.[0]?.d||'')}"></label><label>เวลา<input id="fTime" value="${esc(x?.days?.[0]?.time||'08.00 – 17.00 น.')}"></label><label>ห้องจัดงาน<select id="fRoom">${rooms.map(r=>`<option ${r===(x?.days?.[0]?.room||rooms[0])?'selected':''}>${esc(r)}</option>`).join('')}</select></label><label>จำนวนการันตี<input id="fGuarantee" type="number" value="${Number(x?.guarantee||0)}"></label><label>หน่วย<select id="fUnit"><option ${x?.unit==='ท่าน'?'selected':''}>ท่าน</option><option ${x?.unit==='โต๊ะ'?'selected':''}>โต๊ะ</option><option ${x?.unit==='งาน'?'selected':''}>งาน</option></select></label><label>Sales<select id="fSales">${(staff.sales||[]).map(v=>`<option ${v===(x?.sales||'—')?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label>Event<select id="fEvent">${(staff.event||[]).map(v=>`<option ${v===(x?.event||'—')?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label class="wide">ชุดเมนู<select id="fMenu"><option>ไม่มีอาหาร</option>${menuNames().map(m=>`<option ${m===(x?.days?.[0]?.menu||'')?'selected':''}>${esc(m)}</option>`).join('')}</select></label><label>ราคา/หน่วย<input id="fPrice" type="number" value="${Number(x?.rev?.[0]?.price||0)}"></label></div>
  <div class="form-note">การเลือก “รวม 2 แห่ง” จะไม่ถูกส่งเป็นโรงแรมจริง ระบบจะให้เลือก Queensland หรือ Baiyoke Sky ก่อนบันทึก เพื่อป้องกันปัญหาห้องจัดงาน</div>
  <div class="modal-actions"><button class="ghost" onclick="closeModal()">ยกเลิก</button>${x?`<button class="danger" onclick="deleteEvent('${x.id}')">ลบงาน</button>`:''}<button class="primary" onclick="saveEventForm('${x?.id||''}')">${x?'บันทึกการแก้ไข':'สร้างงาน'}</button></div>`);
}
function changeEventHotel(){const h=document.getElementById('fHotel').value;document.getElementById('fRoom').innerHTML=(BE.settings.ROOMS?.[h]||DEFAULT_ROOMS[h]).map(r=>`<option>${esc(r)}</option>`).join('');}
async function saveEventForm(id){
  const hotel=document.getElementById('fHotel').value;if(hotel!=='QL'&&hotel!=='BY'){toast('กรุณาเลือกโรงแรม');return;}
  const title=document.getElementById('fTitle').value.trim();const date=document.getElementById('fDate').value;if(!title||!date){toast('กรุณากรอกชื่องานและวันที่');return;}
  const old=id?BE.funcs.find(v=>v.id===id):null;const menu=document.getElementById('fMenu').value;
  const x=old||{id:'f_'+Date.now(),depts:clone(BE.settings.DEPTS_BASIC||DEFAULT_DEPTS),rev:[],dep:{amt:0,when:''},prog:[],adj:[]};
  Object.assign(x,{hotel,no:document.getElementById('fNo').value.trim()||String(new Date().getDate())+'/'+(new Date().getMonth()+1),doc:'Draft',status:document.getElementById('fStatus').value,kind:document.getElementById('fKind').value,title,guarantee:Number(document.getElementById('fGuarantee').value||0),unit:document.getElementById('fUnit').value,sales:document.getElementById('fSales').value,event:document.getElementById('fEvent').value,days:[{d:date,time:document.getElementById('fTime').value,room:document.getElementById('fRoom').value,set:'',menu,note:''}],rev:[{n:menu,price:Number(document.getElementById('fPrice').value||0),qty:Number(document.getElementById('fGuarantee').value||1),times:1}]});
  if(!id)BE.funcs.push(x);BE.states[x.id]=BE.states[x.id]||{done:[],photos:[],menuOverrides:{}};
  closeModal();renderEvents();await syncNow();toast(id?'แก้ไขงานแล้ว':'เพิ่มงานแล้ว');
}
async function deleteEvent(id){if(!confirm('ลบใบสั่งงานนี้หรือไม่?'))return;BE.funcs=BE.funcs.filter(x=>x.id!==id);delete BE.states[id];closeModal();renderEvents();await syncNow();toast('ลบงานแล้ว');}
