function renderSettings(){const body=document.getElementById('settingsBody');if(BE.settingsView==='rooms')body.innerHTML=renderRoomsSettings();else body.innerHTML=renderMenusSettings();}
function renderMenusSettings(){const names=menuNames();return `<div class="settings-head"><p>แก้ไข Master Menu ได้โดยไม่กระทบรายการที่แก้เฉพาะ Event</p><button class="primary" onclick="addMasterMenu()">＋ เพิ่มชุดเมนู</button></div><div class="master-list">${names.map((n,i)=>`<details class="master-card"><summary><b>${esc(n)}</b><span>${menuGroups(n).length} กลุ่ม</span></summary><div class="master-body">${menuGroups(n).map((g,gi)=>`<div class="master-group"><div class="group-head"><input value="${esc(g.g)}" onchange="masterGroupName('${esc(n)}',${gi},this.value)"><button class="ghost" onclick="masterAddItem('${esc(n)}',${gi})">＋ รายการ</button></div>${g.items.map((it,ii)=>`<div class="menu-item"><input value="${esc(it)}" onchange="masterItem('${esc(n)}',${gi},${ii},this.value)"><button class="icon danger" onclick="masterRemoveItem('${esc(n)}',${gi},${ii})">×</button></div>`).join('')}<div class="pick-note">${g.pick?`เลือกได้ ${g.pick} รายการ`:'รายการมาตรฐาน (แก้ได้)'}</div></div>`).join('')}<div class="modal-actions"><button class="danger" onclick="deleteMasterMenu('${esc(n)}')">ลบชุดเมนู</button><button class="primary" onclick="saveMasterMenus()">บันทึก Master Menu</button></div></div></details>`).join('')}</div>`;}
function renderRoomsSettings(){const rooms=BE.settings.ROOMS||DEFAULT_ROOMS;return `<div class="settings-head"><p>เพิ่ม/แก้ไขห้องจัดงานของแต่ละโรงแรม</p></div>${['QL','BY'].map(h=>`<div class="room-setting"><h3>${h==='QL'?'Queensland':'Baiyoke Sky'}</h3><div id="rooms-${h}">${(rooms[h]||[]).map((r,i)=>`<div class="menu-item"><input value="${esc(r)}" onchange="editRoom('${h}',${i},this.value)"><button class="icon danger" onclick="removeRoom('${h}',${i})">×</button></div>`).join('')}</div><button class="ghost" onclick="addRoom('${h}')">＋ เพิ่มห้อง</button></div>`).join('')}<div class="modal-actions"><button class="primary" onclick="saveRooms()">บันทึกห้อง</button></div>`;}
function masterGroupName(n,gi,v){masterMenus()[n][gi].g=v;}
function masterAddItem(n,gi){masterMenus()[n][gi].items.push('');renderSettings();}
function masterItem(n,gi,ii,v){masterMenus()[n][gi].items[ii]=v;}
function masterRemoveItem(n,gi,ii){masterMenus()[n][gi].items.splice(ii,1);renderSettings();}
async function saveMasterMenus(){BE.settings.MENUS=masterMenus();await dbSaveSettings();renderSettings();toast('บันทึก Master Menu แล้ว');}
function addMasterMenu(){const n=prompt('ชื่อชุดเมนูใหม่');if(!n)return;masterMenus()[n]=[{g:'อาหาร',items:[''],on:['']}];renderSettings();}
async function deleteMasterMenu(n){if(!confirm('ลบชุดเมนู '+n+' ?'))return;delete masterMenus()[n];await dbSaveSettings();renderSettings();toast('ลบชุดเมนูแล้ว');}
function editRoom(h,i,v){BE.settings.ROOMS[h][i]=v;}
function addRoom(h){BE.settings.ROOMS[h].push('ห้องใหม่');renderSettings();}
function removeRoom(h,i){BE.settings.ROOMS[h].splice(i,1);renderSettings();}
async function saveRooms(){await dbSaveSettings();renderSettings();toast('บันทึกห้องแล้ว');}
